# -*- coding: utf-8 -*-
"""
Created on Thu Jun  6 10:24:56 2019

@author: thibault poncetta

ASCII table personalisée
"""
def FX33(n):
    if n==0:
        return "▲"
    elif n==1:
        return "▼"
    elif n==2:
        return "!"
    elif n==3:
        return "'"
    elif n==4:
        return "#"
    elif n==5:
        return "$"
    elif n==6:
        return "%"
    elif n==7:
        return "&"
    elif n==8:
        return "("
    elif n==9:
        return "*"
    elif n==10:
        return ")"
    elif n==11:
        return "+"
    elif n==12:
        return ","
    elif n==13:
        return "-"
    elif n==14:
        return "."
    elif n==15:
        return "/"
    elif n==16:
        return "0"
    elif n==17:
        return "1"
    elif n==18:
        return "2"
    elif n==19:
        return "3"
    elif n==20:
        return "4"
    elif n==21:
        return "5"
    elif n==22:
        return "6"
    elif n==23:
        return "7"
    elif n==24:
        return "8"
    elif n==25:
        return "9"
    elif n==26:
        return ":"
    elif n==27:
        return ";"
    elif n==28:
        return "<"
    elif n==29:
        return ">"
    elif n==30:
        return "?"
    elif n==31:
        return "@"
    elif n==32:
        return "A"
    elif n==33:
        return "B"
    elif n==34:
        return "C"
    elif n==35:
        return "D"
    elif n==36:
        return "E"
    elif n==37:
        return "F"
    elif n==38:
        return "G"
    elif n==39:
        return "H"
    elif n==40:
        return "I"
    elif n==41:
        return "J"
    elif n==42:
        return "K"
    elif n==43:
        return "L"
    elif n==44:
        return "M"
    elif n==45:
        return "N"
    elif n==46:
        return "O"
    elif n==47:
        return "P"
    elif n==48:
        return "Q"
    elif n==49:
        return "R"
    elif n==50:
        return "S"
    elif n==51:
        return "T"
    elif n==52:
        return "U"
    elif n==53:
        return "V"
    elif n==54:
        return "W"
    elif n==55:
        return "X"
    elif n==56:
        return "Y"
    elif n==57:
        return "Z"
    elif n==58:
        return "û"
    elif n==59:
        return "ù"
    elif n==60:
        return "ÿ"
    elif n==61:
        return "Ö"
    elif n==62:
        return "Ü"
    elif n==63:
        return "¢"
    elif n==64:
        return "£"
    elif n==65:
        return "¥"
    elif n==66:
        return "₧"
    elif n==67:
        return "ƒ"
    elif n==68:
        return "á"
    elif n==69:
        return "í"
    elif n==70:
        return "ó"
    elif n==71:
        return "ú"
    elif n==72:
        return "ñ"
    elif n==73:
        return "Ñ"
    elif n==74:
        return "º"
    elif n==75:
        return "⌐"
    elif n==76:
        return "¬"
    elif n==77:
        return "¼"
    elif n==78:
        return "¡"
    elif n==79:
        return "«"
    elif n==80:
        return "»"
    else:
        return "error"
    
def FX33_reverse(n):
    if n=="▲":
        return 0
    elif n=="▼":
        return 1
    elif n=="!":
        return 2
    elif n=="'":
        return 3
    elif n=="#":
        return 4
    elif n=="$":
        return 5
    elif n=="%":
        return 6
    elif n=="&":
        return 7
    elif n=="(":
        return 8
    elif n=="*":
        return 9
    elif n==")":
        return 10
    elif n=="+":
        return 11
    elif n==",":
        return 12
    elif n=="-":
        return 13
    elif n==".":
        return 14
    elif n=="/":
        return 15
    elif n=="0":
        return 16
    elif n=="1":
        return 17
    elif n=="2":
        return 18
    elif n=="3":
        return 19
    elif n=="4":
        return 20
    elif n=="5":
        return 21
    elif n=="6":
        return 22
    elif n=="7":
        return 23
    elif n=="8":
        return 24
    elif n=="9":
        return 25
    elif n==":":
        return 26
    elif n==";":
        return 27
    elif n=="<":
        return 28
    elif n==">":
        return 29
    elif n=="?":
        return 30
    elif n=="@":
        return 31
    elif n=="A":
        return 32
    elif n=="B":
        return 33
    elif n=="C":
        return 34
    elif n=="D":
        return 35
    elif n=="E":
        return 36
    elif n=="F":
        return 37
    elif n=="G":
        return 38
    elif n=="H":
        return 39
    elif n=="I":
        return 40
    elif n=="J":
        return 41
    elif n=="K":
        return 42
    elif n=="L":
        return 43
    elif n=="M":
        return 44
    elif n=="N":
        return 45
    elif n=="O":
        return 46
    elif n=="P":
        return 47
    elif n=="Q":
        return 48
    elif n=="R":
        return 49
    elif n=="S":
        return 50
    elif n=="T":
        return 51
    elif n=="U":
        return 52
    elif n=="V":
        return 53
    elif n=="W":
        return 54
    elif n=="X":
        return 55
    elif n=="Y":
        return 56
    elif n=="Z":
        return 57
    elif n=="û":
        return 58
    elif n=="ù":
        return 59
    elif n=="ÿ":
        return 60
    elif n=="Ö":
        return 61
    elif n=="Ü":
        return 62
    elif n=="¢":
        return 63
    elif n=="£":
        return 64
    elif n=="¥":
        return 65
    elif n=="₧":
        return 66
    elif n=="ƒ":
        return 67
    elif n=="á":
        return 68
    elif n=="í":
        return 69
    elif n=="ó":
        return 70
    elif n=="ú":
        return 71
    elif n=="ñ":
        return 72
    elif n=="Ñ":
        return 73
    elif n=="º":
        return 74
    elif n=="⌐":
        return 75
    elif n=="¬":
        return 76
    elif n=="¼":
        return 77
    elif n=="¡":
        return 78
    elif n=="«":
        return 79
    elif n=="»":
        return 80
    else:
        return "error"
